### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by toppyy** [TiraLabra/minesweeper#56]
Projekti ladattu 10.2.2020 / 16.10

**“gradle build”  antaa seuraavat virheet:**

    minesweeper/bot/RTiraBot.java:7: error: package min.minesweeper.bot does not exist
    import min.minesweeper.bot.Reunat;

    minesweeper/bot/Reunat.java:66: error: cannot find symbol
        if(q != 0){
    symbol:   variable q
    location: class Reunat
    
    TiraBot.java:91: error: cannot find symbol
    Reunat r = new Reunat();
    ^
    symbol:   class Reunat
    location: class TiraBot

**Johdonmukainen kieli:**
Projektissa voisi käyttää johdonmukaisesti joko englantia tai suomea. Luokkien/metodien/muuttujien nimissä kieli vaihtelee englannin ja suomen välillä.

**Luokkien kommentoinnista:**
Kommentointiin voisi vielä kiinnittää hieman huomiota. Esimerkiksi luokan minesweeper/bot/TiraBot.java kommentti on vissiinkin kopio projektipohjan testibotin kommentista. Olisi mukavaa jos tässä olisi suusanallinen selostus omasta botin logiikan toteutuksesta. Myös esim. Valitsija-luokan metodeilla on sama kuvaus. 

**Nimeämisestä:**
Nimissä voisi olla hieman monisanaisempi ja samalla välttää liian samankaltaisia nimiä. Nyt esim. Reunat-luokalla on metodit nimeltä laske ja laskeu. Vastaavasti esim. TiraBot -luokan metodissa getPossibleMoves on HashSetit nimeltä pairs ja pairss.  Helpottaisi ohjelman lukua ja ymmärtämistä, jos olisi selkeämmät, kuvaavat nimet. 

**Luokista:**
Voisiko harkita, että ko. Luokka toteutettaisiin osana Board-luokkaa? Nythän ko. Luokan metodit ovat luonteeltaan vähän samankaltaisia kuin board.getOpenSquares. Eli tällöin olisi esimerkiksi board.getOpenSquaresWithAdjacentMines? 
Samoin pohtisin myös Valitsija luokan integroimista TiraBot -luokkaan? Voisiko ajatella, että bottin on valitsija?

**Kommentoitu koodi pois**
Ei pois kommentoitua koodia mukaan (kts. Esim. Luokka Tirabot)

**Comment by saskeli** [comment]
Nyt tuli issue väärään repoon. Tämä on nimenomaan se projektipohja eikä opiskelijan projekti. Sisällöstä tosin voi päätellä että kommentit liittyvät oikeaan projektiin

**Comment by toppyy** [comment]
Äh, sori. Oli kumpikin auki kun tarkastelin, että mikä pätkä oli pohjasta ja mikä opiskelijan projektista. 

Labtoolsista ei saa näköjään enää vaihdettua linkkiä vertaisarviointiin. No, ilmeisesti tuosta käy arvioijalle ilmi kuitenkin oikea repo. Loin issuen uudestaan (toivottavasti) oikeaan repooon.
